import argparse
import dataclasses
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, List

DIR = Path(__file__).parent.resolve()

BAD_IDENT_CHARS = {
    '*',
    '(', ')',
    '[', ']',
}


@dataclass
class Parameter:
    name: Optional[str]
    type: str


@dataclass
class Function:
    name: str
    args: list[Parameter]
    ret: str

    # namespace: str
    # idx: int

    def identifier_safe_name(self):
        name = self.name.replace(' ', '_')

        if BAD_IDENT_CHARS.intersection(name):
            for c in BAD_IDENT_CHARS:
                name = name.replace(c, '_')

        return name

    # def var_name(self):
    #    return f"ptr{self.idx:03d}_{self.identifier_safe_name()}"


@dataclass
class JsonData:
    functions: list[Function]


def main():
    argparser = argparse.ArgumentParser()
    argparser.add_argument('--plugin-impl-c', type=str)
    argparser.add_argument('--export-impl-c', type=str)
    args = argparser.parse_args()

    with open(DIR / 'lua_functions.json') as f:
        data = json.load(f)

        functions: List[Function] = []
        for fn in data['functions']:
            fn['args'] = [Parameter(**p) for p in fn['args']]
            functions.append(Function(**fn))

    plugin_stub_code = ""
    struct_entry_str = ""
    init_func_body = ""
    export_func_body = ""

    for f in functions:
        # lua_setlevel doesn't appear anywhere other than in lua.h, it has no implementation - what's it for?
        if f.name == 'lua_setlevel':
            continue

        effective_args = []
        for arg in f.args:
            arg_name = arg.name
            if not arg_name:
                arg_name = f'anon_arg_{len(effective_args) + 1}'
            effective_args.append(Parameter(arg_name, arg.type))

        param_str = ', '.join([f'{param.type} {param.name}' for param in effective_args])
        args_str = ', '.join([param.name for param in effective_args])

        plugin_stub_code += f"""
{f.ret} {f.name}({param_str}) {{
    return LUA_FUNCTION_TABLE.{f.name}({args_str});
}}
""".strip() + "\n"

        struct_entry_str += (" " * 4) + f"{f.ret} (*{f.name})({param_str});\n"

        init_func_body += f"""    LUA_FUNCTION_TABLE.{f.name} = (decltype(LUA_FUNCTION_TABLE.{f.name})) loadFn("{f.name}");\n"""

        export_func_body += f"""
    if (name == "{f.name}")
        return &{f.name};
"""[1:]

    body = f"""
// AUTO-GENERATED BY gen_lua_bindings.py - DO NOT EDIT
// Generated by the SBLT build for inclusion in the plugin SDK.

#include "lua.h"
#include "lauxlib.h"

struct LuaPluginFunctionTable {{
{struct_entry_str}
}} LUA_FUNCTION_TABLE = {{}};

void SBLT_LUA_INIT_FUNC_TABLE(void* (*loadFn)(const char*)) {{
{init_func_body}
}}

{plugin_stub_code}
""".strip() + "\n"

    export_body = f"""
// AUTO-GENERATED BY gen_lua_bindings.py - DO NOT EDIT

#include "lua.h"
#include "lauxlib.h"
#include "plugins/plugins.h"

void* blt::plugins::GetLuaFnByNameGenerated(const std::string &name) {{
{export_func_body}
    return nullptr;
}}
""".strip() + "\n"

    # print(body)
    if args.plugin_impl_c:
        with open(args.plugin_impl_c, 'w') as fi:
            fi.write(body)

    if args.export_impl_c:
        with open(args.export_impl_c, 'w') as fi:
            fi.write(export_body)


if __name__ == '__main__':
    main()
